name: Client startup

on: [ workflow_dispatch ]

jobs:
  runJar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Подключение Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Настройка доступа к gradlew
        run: chmod +x ./gradlew
      - name: Сборка плагина в jar
        run: ./gradlew jar
      - name: Запуск Jar файла
        run: java -jar build/libs/uwu.jar
